server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: health-track
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: 'postgres'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password